### PR TITLE
Do not fetch from localhost port 9130 RMB-914

### PR DESCRIPTION
**Pull request by adamdickmeiss**
Insecure and bad style to call Okapi like this when parsing RAML.

## Purpose

Avoid calling another service which is not part of testing or reliably available.

### CODE REVIEW

**Review by julianladisch — APPROVED** [review]
Looks good, thanks!

**Review by dcrossleyau — DISMISSED** [review]

**Review by dcrossleyau — COMMENTED** [review]
Oh, i did approve too early.

I have never understood this feature. I gather that it is related to ramls/ramls.raml and ramls/jsonSchemas.raml files.

The api-lint also has troubles with those, and that is why those files are excluded in Jenkinsfile.

The changes in this PR mean that those referenced resources are not found at those relative paths, e.g. user.sample and userdataCollection.json etc are not in this directory.

**Comment by adamdickmeiss** [comment]
How about we remove those sample files entirely and the references to them ?

**Comment by dcrossleyau** [comment]
I agree.

**Comment by dcrossleyau** [comment]
Drat. That cla thing again. If you are ready to merge, then i will use Admin privs to override it.

**Pull request merged**
