### PR TITLE
Cql schema

### PR DESCRIPTION
**Pull request by skoczko**
Add ignorable CODEX extended CQL schema

### CODE REVIEW

**Comment by MikeTaylor** [comment]
Looking good. But where does `codex_instance_cqlschema-ext.json` get referenced by another file?

There seems to be some conflation between the definition of a context-set (which is what the new file does) and of an entire CQL schema (which is what the old file does -- though now it also has a single context set defined within it).

I would have expected to see `codex_instance_cqlschema.json` not saying anything about indexes, but importing or otherwise referencing both `codex_instance_cqlschema-ext.json` and another similar file that defines the main "codex" context set. Something like:

```
{
  "name": "CODEX Instance CQL Schema",
  "description": "Required indexes and operators in CODEX instance search. Providers should report any unsupported indexes/relations as errors.",
  "contextSets": {
    "codex": "codex_contextset_codex.json",
    "ext": "codex_contextset_ext.json"
  },
  "defaultContextSet": "codex",
  "operators": [ ... ]
}
```

**Comment by skoczko** [comment]
The idea here is that the "codex" (which you rightly notice is more than a context set, it also captures a schema for booleans which in CQL spec is only defined through a very limited "conformance level") defines the basic required support for all providers. While "ext" defines anything beyond that and its support is optional. 

So I would expect that eventually we have multiple "ext" schemas, some of them bringing support for things like bool operators and nesting. E.g the local inventory can already provide such support.

**Comment by MikeTaylor** [comment]
What would it mean for a CQL query (when translated into JSON, obviously) to "conform" to one of these schemas? Or to both?

**Comment by skoczko** [comment]
I didn't consider the CQL Schema to be a JSON Schema per-se, able to validate some imaginary CQL-in-JSON encoding (though this would be an interesting approach!). I only consider it to be a more rigorous (compared to a free-form text document) declaration of supported CQL syntax and semantics.

Conforming to both would mean supporting the superset of functionality -- e.g assuming the "ext" schema defines "AND", the provider supporting "codex" and "ext" would include support for "AND".

**Comment by skoczko** [comment]
What makes it tricky to take the approach you are proposing (albeit closer to the nature of the CQL spec) is the fact that, I think, we need to express the notion of "filter" indexes. A special kind of indexes that can be applied to the rest of the query (through an AND) even when the backend does not support free-form booleans or nesting. Here the notion of a context set (name of the index) gets intertwined with the structure of the query.

**Comment by MikeTaylor** [comment]
OK, so this is a human-readable document, targeted to human readers, even though it's in a machine-readable format.

I think we could work through this and find a good, rigorous way of expressing exactly what we mean, with context sets, filters and the rest. _But_ given that no actual software will consume this, I think we can just say it's Good Enough as it is, and move on with our lives. (If we want to change to format later, we'll be able to do so without breaking anything.)

**Comment by MikeTaylor** [comment]
Hi, @sduvvuri-ebsco. This is to support the Codex contract document, which is still in prep, but very close to being ready to publish. See its present version at https://github.com/folio-org/ui-search/blob/master/doc/codex-contract.md -- espcially section 3 on queries. In a nutshell, the purpose of the "extension" context-set is to provide an explicit way of marking a particular index (such as `ext.selected`) as optional.

**Comment by sduvvuri-ebsco** [comment]
@MikeTaylor : Thanks for your comment Mike! Not sure if this is a question for you or for @skoczko but here it is: Per our previous conversation, https://docs.google.com/spreadsheets/d/1s4cMdQEThNH4v-3VpyoNpsZkY3uB1OGomQ99L2o5uVA/edit#gid=0, selected can have "all", "true" or "false" where as per this schema, it can have values "both", "yes" or "no". Could you please clarify which one we want to stick to? Thanks!!

**Comment by MikeTaylor** [comment]
I don't think it's something we feel strongly about -- AFAIK, @skoczko just wrote down what occurred to him at the time. At any rate, if you prefer that we use `all`/`true`/`false`, that's fine by me. Just so long as we're on the same page!

**Comment by sduvvuri-ebsco** [comment]
Sure, thanks @MikeTaylor , let's stick to what is in the spreadsheet since we have already written code that adheres to it. I will create a new pull request, thanks!!

**Pull request merged**
