### PR TITLE
Fix lint errors in raml related to codex - instance and instanceCollection schemas

### PR DESCRIPTION
**Pull request by sduvvuri-ebsco**
## Purpose
On this https://github.com/folio-org/mod-codex-ekb/pull/72, saw a few raml-related lint errors that had to do with instance.json and instanceCollection.json in codex raml. This PR fixes those.

## Approach
- Add descriptions in RAML in instance.json and instanceCollection.json

### CODE REVIEW

**Review by dcrossleyau — CHANGES_REQUESTED** [review]
The "schema description" changes will be done on the "raml1" branch. See [FOLIO-1554](https://issues.folio.org/browse/FOLIO-1554).

**Review by dcrossleyau — APPROVED** [review]

**Comment by dcrossleyau** [comment]
Of course you could merge this. But the main place that we want to fix all this stuff is the "raml1" branch.

**Review by carolegodfrey — APPROVED** [review]

**Comment by sduvvuri-ebsco** [comment]
Sounds good @dcrossleyau! Reading through your comments, my understanding is that you are going to port the changes in this PR to RAML1.0 branch. Please let me know if you want me to do anything from my end..

**Comment by dcrossleyau** [comment]
Yes that is already done in #104
Thanks.

**Pull request merged**
