### PR TITLE
Better description and example for the "searchable" trait

### PR DESCRIPTION
**Pull request by MikeTaylor**
This arises from a discussion with Seb and Heikki on the #staff channel. I don't know whether there are special requirements on the format of these parts of a RAML trait, so I'd like Shale to check this before merging.

### CODE REVIEW

**Comment by dcrossleyau** [comment]
I have investigated this. Using raml-cop shows that the various RAML files that use "searchable" (e.g. 'raml-cop ramls/mod-users/users.raml') would then need their current example and description to be removed.

Also the Description can use Markdown, so for example we can link to the CQL resources.

I can attend to this tomorrow.

**Comment by dcrossleyau** [comment]
That would mean that all RAML docs would show that same example, which would not be relevant in all situations.

For example, mod-inventory-storage [item-storage.raml](https://github.com/folio-org/mod-inventory-storage/blob/master/ramls/item-storage.raml) has its own specific example.

Using this raml-util/traits/searchable.raml would enable a high-level description about CQL and link to the Glossary (added your CQL example there) followed by their local description and example:

```
      queryParameters:
        query:
          description: |
            A query expressed as a CQL string
            (see [dev.folio.org/doc/glossary#cql](http://dev.folio.org/doc/glossary#cql)).

            <<description>>
          example: |
            <<example>>
          required: false
```

The blank line separates their description (which can be an empty string) from the high-level description.

**Comment by MikeTaylor** [comment]
So does `<<example>>` mean "interpolate the value of the `example` argument provided in this trait's invocation? If so, I _guess_ it's OK to leave it at that -- although it seems better to me to give some example of what queries look like, even if the specific fields involved are not those supported by the particular module whose RAML is using the trait.

**Comment by dcrossleyau** [comment]
Yes, that is what any `<<...>>` means.

I found a solution -- in the raml-util "description" explain the first general example. Their specific description and example can follow, or be empty.

**Comment by dcrossleyau** [comment]
Perhaps because it is your PR. I will add some more tweaks and merge it.

**Pull request merged**
