### PR TITLE
FOLIO-351 whitespace tidy 6

### PR DESCRIPTION
**Pull request by dcrossleyau**

### CODE REVIEW

**Comment by dcrossleyau** [comment]
I use a local shell script with find and grep to scan all relevant text files.

I do use jq in some situations to reformat JSON consistently.

**Comment by dcrossleyau** [comment]
Thanks for your review @carolegodfrey. These days it needs someone else with write access to do an approved review. Help please.

**Comment by carolegodfrey** [comment]
@dcrossleyau I reviewed but didn't merge pull request (in the past we have left the merger up to the individual that submitted the pull request) Please let me know if this is still the best practice

**Comment by dcrossleyau** [comment]
Thanks, now i can proceed. Yes, i think that that approach is good.

**Comment by dcrossleyau** [comment]
Thanks, now i can proceed. Yes, i think that that approach is good.

**Pull request merged**
